# ------------------------------------------------------------------------------
# backup.yml
# ------------------------------------------------------------------------------

# Playbook for creating backups of the DATA web application on the Ansible
# controller machine. Currently the combination of subdomains and hosts for
# those subdomains is hard coded in this script. Perhaps this could be derived
# from the Ansible group and host vars configured instead.

---

- hosts: gateway, prod1

  vars:
    backup_date: "{{ ansible_date_time.date }}"

  vars_prompt:
    - name: subdomain
      prompt: "Enter the subdomain to backup"
      private: false

  tasks:

    - name: Ensure directory for backups from the subdomain is present
      ansible.builtin.file:
        path: backups/{{ subdomain }}
        state: directory
      delegate_to: localhost
      when: subdomain in [ 'test', 'www' ]

    - block:

        - ansible.builtin.synchronize:
            mode: pull
            src: /var/local/www-data/{{ item }}
            dest: backups/www/{{ backup_date }}/
            rsync_opts:
              - '--chmod=D755'
              - '--chmod=F644'
          loop:
            - derbyartsandtheatre.db
            - upload

      when: subdomain == 'www' and inventory_hostname == 'prod1'

    - block:

        - ansible.builtin.synchronize:
            mode: pull
            src: "{{ item }}"
            dest: backups/test/{{ backup_date }}/
            rsync_opts:
              - '--chmod=D755'
              - '--chmod=F644'
          loop:
            - /var/www/test.{{ domain }}/database/derbyartsandtheatre.db
            - /var/www/test.{{ domain }}/html/upload

      when: subdomain == 'test' and inventory_hostname == 'gateway'
