# ------------------------------------------------------------------------------
# install.yml
# ------------------------------------------------------------------------------

# Install an instance of the DATA web application across one or more hosts.

---

- hosts: gateway, prod1

  handlers:

    - name: Restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted
      become: yes
      delegate_to: hub

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: yes

    - name: Restart uwsgi
      ansible.builtin.service:
        name: uwsgi
        state: restarted
      become: yes

  tasks:

    - ansible.builtin.import_tasks: validation.yml

    - ansible.builtin.import_tasks: 
        file: ./admin/install.yml
      tags: admin

    - block:

        - name: Add a dynamic DNS entry for the admin web service
          ansible.builtin.import_role:
            name: dynamic_dns
            tasks_from: create-record
          delegate_to: gateway
          delegate_facts: true
          vars:
            domain_name: "{{ domain }}"
            dns_record_hostname: "admin\
              {% if subdomain != 'www' %}{{ '.' + subdomain }}{% endif %}"

        - ansible.builtin.import_tasks:
            file: ./admin_web/install.yml

        - name: Add DNS record for the admin web service
          ansible.builtin.lineinfile:
            path: /etc/addn-hosts
            line: "{{ ansible_default_ipv4.address }} {{ admin_server_name }}"
          notify: Restart dnsmasq
          delegate_to: hub
          become: yes

      tags: admin_web

    - ansible.builtin.import_tasks:
        file: ./app/install.yml
      tags: app

    - block:

        - name: Add a dynamic DNS entry for the app web service
          ansible.builtin.import_role:
            name: dynamic_dns
            tasks_from: create-record
          delegate_to: gateway
          delegate_facts: true
          vars:
            domain_name: "{{ domain }}"
            dns_record_hostname: "{{ subdomain }}"

        - ansible.builtin.import_tasks:
            file: ./app_web/install.yml

        - name: Add DNS record for the app web service
          ansible.builtin.lineinfile:
            path: /etc/addn-hosts
            line: "{{ ansible_default_ipv4.address }} {{ server_name }}"
          notify: Restart dnsmasq
          delegate_to: hub
          become: yes

      tags: app_web
